-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 13:05:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AksumDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AksumDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aksum` DEFAULT CHARACTER SET utf8 ;
USE `aksum` ;

-- -----------------------------------------------------
-- Table `AksumDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`user` ;

CREATE TABLE IF NOT EXISTS `aksum`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `courriel` VARCHAR(45) NULL,
  `addresse` VARCHAR(45) NULL,
  `mdp` VARCHAR(120) NULL,
  `privilege` INT(11) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUser_UNIQUE` ON `aksum`.`user` (`idUser` ASC);


-- -----------------------------------------------------
-- Table `AksumDB`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`item` ;

CREATE TABLE IF NOT EXISTS `aksum`.`item` (
  `iditem` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NULL,
  `auteur` VARCHAR(45) NULL,
  `prix` INT NULL,
  `dispo` VARCHAR(45) NULL,
  `itemcol` VARCHAR(45) NULL,
  `photo` BLOB NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`iditem`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idItem_UNIQUE` ON `aksum`.`item` (`idItem` ASC);


-- -----------------------------------------------------
-- Table `AksumDB`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`panier` ;

CREATE TABLE IF NOT EXISTS `AksumDB`.`panier` (
  `idpanier` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NULL,
  `iditem` INT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idpanier`),
  CONSTRAINT `fk_panier_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `aksum`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_panier_user1_idx` ON `aksum`.`panier` (`user_idUser` ASC);


-- -----------------------------------------------------
-- Table `AksumDB`.`panierGuest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`panierGuest` ;

CREATE TABLE IF NOT EXISTS `aksum`.`panierGuest` (
  `idpanier` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NULL,
  `iditem` INT NULL,
  PRIMARY KEY (`idpanier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AksumDB`.`guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`guest` ;

CREATE TABLE IF NOT EXISTS `aksum`.`guest` (
  `idguest` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idguest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AksumDB`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`commande` ;

CREATE TABLE IF NOT EXISTS `aksum`.`commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `idpanier` INT NULL,
  `date` DATETIME NULL,
  `price` INT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  CONSTRAINT `fk_commande_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `aksum`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commande_panier1_idx` ON `aksum`.`commande` (`panier_idpanier` ASC);


-- -----------------------------------------------------
-- Table `AksumDB`.`commandeGuest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`commandeGuest` ;

CREATE TABLE IF NOT EXISTS `aksum`.`commandeGuest` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `price` INT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `addresse1` VARCHAR(45) NULL,
  `addresse2` VARCHAR(45) NULL,
  `courriel` VARCHAR(45) NULL,
  `guest_idguest` INT NOT NULL,
  `panierGuest_idpanier` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  CONSTRAINT `fk_commandeGuest_guest1`
    FOREIGN KEY (`guest_idguest`)
    REFERENCES `aksum`.`guest` (`idguest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandeGuest_panierGuest1`
    FOREIGN KEY (`panierGuest_idpanier`)
    REFERENCES `aksum`.`panierGuest` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commandeGuest_guest1_idx` ON `aksum`.`commandeGuest` (`guest_idguest` ASC);

CREATE INDEX `fk_commandeGuest_panierGuest1_idx` ON `aksum`.`commandeGuest` (`panierGuest_idpanier` ASC);


-- -----------------------------------------------------
-- Table `AksumDB`.`panier_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`panier_has_item` ;

CREATE TABLE IF NOT EXISTS `aksum`.`panier_has_item` (
  `panier_idpanier` INT NOT NULL,
  `item_iditem` INT NOT NULL,
  PRIMARY KEY (`panier_idpanier`, `item_iditem`),
  CONSTRAINT `fk_panier_has_item_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `aksum`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panier_has_item_item1`
    FOREIGN KEY (`item_iditem`)
    REFERENCES `aksum`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_panier_has_item_item1_idx` ON `aksum`.`panier_has_item` (`item_iditem` ASC);

CREATE INDEX `fk_panier_has_item_panier1_idx` ON `aksum`.`panier_has_item` (`panier_idpanier` ASC);


-- -----------------------------------------------------
-- Table `AksumDB`.`panierGuest_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aksum`.`panierGuest_has_item` ;

CREATE TABLE IF NOT EXISTS `aksum`.`panierGuest_has_item` (
  `panierGuest_idpanier` INT NOT NULL,
  `item_iditem` INT NOT NULL,
  PRIMARY KEY (`panierGuest_idpanier`, `item_iditem`),
  CONSTRAINT `fk_panierGuest_has_item_panierGuest1`
    FOREIGN KEY (`panierGuest_idpanier`)
    REFERENCES `aksum`.`panierGuest` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panierGuest_has_item_item1`
    FOREIGN KEY (`item_iditem`)
    REFERENCES `aksum`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_panierGuest_has_item_item1_idx` ON `aksum`.`panierGuest_has_item` (`item_iditem` ASC);

CREATE INDEX `fk_panierGuest_has_item_panierGuest1_idx` ON `aksum`.`panierGuest_has_item` (`panierGuest_idpanier` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
